#ifndef datos_h
#define datos_h
void mostrar_menu_figuras();
int pedir_opcion();
void repito();
void triangulo();
void paralelogramo();
void cuadrado();
void rectangulo();
void rombo();
void trapecio();
void circulo();
void poligono_regular();
void cubo();
void cuboide();
void cilindro();
void esfera();
void cono();
#endif
